/* ═══════════════════════════════════════════════════════════════
   Lazy loader for per-module data (lesson content + question banks).
   window.LAZY_MANIFEST ({path: hash}) is generated by tools/stamp-assets.js,
   so every file is fetched as path?v=<hash> and can be cached as immutable.
   ═══════════════════════════════════════════════════════════════ */

window.Lazy = (() => {
  const manifest = () => window.LAZY_MANIFEST || {};
  const pending = new Map();

  function load(path) {
    if (pending.has(path)) return pending.get(path);
    const p = new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = path + (manifest()[path] ? '?v=' + manifest()[path] : '');
      s.onload = () => resolve();
      s.onerror = () => { pending.delete(path); reject(new Error('Failed to load ' + path)); };
      document.head.appendChild(s);
    });
    pending.set(path, p);
    return p;
  }

  // Content (mNN-*.js) and questions (qNN-*.js) for a module number like "05"
  function module(number) {
    const prefixes = [`data/content/m${number}-`, `data/questions/q${number}-`];
    const files = Object.keys(manifest()).filter(f => prefixes.some(p => f.startsWith(p)));
    return Promise.all(files.map(load));
  }

  return { load, module };
})();
